'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WhisperServerGUI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 Advanced Settings 的本地化字符串。
        '''</summary>
        Public ReadOnly Property AdvancedSettingsExpander() As String
            Get
                Return ResourceManager.GetString("AdvancedSettingsExpander", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Whisper Local Server Assistant 的本地化字符串。
        '''</summary>
        Public ReadOnly Property AppTitle() As String
            Get
                Return ResourceManager.GetString("AppTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Audio Context Size: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property AudioContextLabel() As String
            Get
                Return ResourceManager.GetString("AudioContextLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Basic Settings 的本地化字符串。
        '''</summary>
        Public ReadOnly Property BasicSettingsExpander() As String
            Get
                Return ResourceManager.GetString("BasicSettingsExpander", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Beam Size: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property BeamSizeLabel() As String
            Get
                Return ResourceManager.GetString("BeamSizeLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Best Of: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property BestOfLabel() As String
            Get
                Return ResourceManager.GetString("BestOfLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Browse 的本地化字符串。
        '''</summary>
        Public ReadOnly Property BrowseButton() As String
            Get
                Return ResourceManager.GetString("BrowseButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Browse... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property BrowseDotsButton() As String
            Get
                Return ResourceManager.GetString("BrowseDotsButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Cancel 的本地化字符串。
        '''</summary>
        Public ReadOnly Property CancelTranscriptionButton() As String
            Get
                Return ResourceManager.GetString("CancelTranscriptionButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Clear 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ClearFilesButton() As String
            Get
                Return ResourceManager.GetString("ClearFilesButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Concurrency: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ConcurrencyLabel() As String
            Get
                Return ResourceManager.GetString("ConcurrencyLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Configuration 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ConfigTabHeader() As String
            Get
                Return ResourceManager.GetString("ConfigTabHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Convert Audio to WAV (Requires ffmpeg) 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ConvertAudioCheckBox() As String
            Get
                Return ResourceManager.GetString("ConvertAudioCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 CSV file saved to: {0} 的本地化字符串。
        '''</summary>
        Public ReadOnly Property CsvFileSavedTo() As String
            Get
                Return ResourceManager.GetString("CsvFileSavedTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Debug Mode 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DebugModeCheckBox() As String
            Get
                Return ResourceManager.GetString("DebugModeCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Exit After Language Detection 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DetectLanguageCheckBox() As String
            Get
                Return ResourceManager.GetString("DetectLanguageCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Diarize (Stereo Audio) 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DiarizeCheckBox() As String
            Get
                Return ResourceManager.GetString("DiarizeCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Drag and drop audio files here or click Browse to select files 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DropAreaText() As String
            Get
                Return ResourceManager.GetString("DropAreaText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 DTW Model: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DTWLabel() As String
            Get
                Return ResourceManager.GetString("DTWLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Audio Processing Duration (ms): 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DurationLabel() As String
            Get
                Return ResourceManager.GetString("DurationLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Entropy Threshold: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property EntropyThresholdLabel() As String
            Get
                Return ResourceManager.GetString("EntropyThresholdLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Error: {0} 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ErrorGeneral() As String
            Get
                Return ResourceManager.GetString("ErrorGeneral", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Server Status: Error - Model file not found 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ErrorModelFileNotFound() As String
            Get
                Return ResourceManager.GetString("ErrorModelFileNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Error opening browser: {0} 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ErrorOpeningBrowser() As String
            Get
                Return ResourceManager.GetString("ErrorOpeningBrowser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Error parsing JSON for CSV: {0} 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ErrorParsingJsonForCsv() As String
            Get
                Return ResourceManager.GetString("ErrorParsingJsonForCsv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 [{0}] Error reading stream: {1} 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ErrorReadingStream() As String
            Get
                Return ResourceManager.GetString("ErrorReadingStream", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Error saving CSV file: {0} 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ErrorSavingCsvFile() As String
            Get
                Return ResourceManager.GetString("ErrorSavingCsvFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Server Status: Error - Server executable not found 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ErrorServerExecutableNotFound() As String
            Get
                Return ResourceManager.GetString("ErrorServerExecutableNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Server Status: Error - Server not responding after 20 seconds 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ErrorServerNotResponding() As String
            Get
                Return ResourceManager.GetString("ErrorServerNotResponding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Error transcribing file: {0} 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ErrorTranscribingFile() As String
            Get
                Return ResourceManager.GetString("ErrorTranscribingFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 [File saved to: {0}] 的本地化字符串。
        '''</summary>
        Public ReadOnly Property FileSavedTo() As String
            Get
                Return ResourceManager.GetString("FileSavedTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Skipped existing file 的本地化字符串。
        '''</summary>
        Public ReadOnly Property FileSkippedExists() As String
            Get
                Return ResourceManager.GetString("FileSkippedExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Flash Attention 的本地化字符串。
        '''</summary>
        Public ReadOnly Property FlashAttentionCheckBox() As String
            Get
                Return ResourceManager.GetString("FlashAttentionCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Host: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property HostLabel() As String
            Get
                Return ResourceManager.GetString("HostLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Inference Path: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property InferencePathLabel() As String
            Get
                Return ResourceManager.GetString("InferencePathLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Inference 的本地化字符串。
        '''</summary>
        Public ReadOnly Property InferenceTabHeader() As String
            Get
                Return ResourceManager.GetString("InferenceTabHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Auto 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LanguageAuto() As String
            Get
                Return ResourceManager.GetString("LanguageAuto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Chinese 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LanguageChinese() As String
            Get
                Return ResourceManager.GetString("LanguageChinese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 English 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LanguageEnglish() As String
            Get
                Return ResourceManager.GetString("LanguageEnglish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 French 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LanguageFrench() As String
            Get
                Return ResourceManager.GetString("LanguageFrench", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 German 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LanguageGerman() As String
            Get
                Return ResourceManager.GetString("LanguageGerman", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Japanese 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LanguageJapanese() As String
            Get
                Return ResourceManager.GetString("LanguageJapanese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Korean 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LanguageKorean() As String
            Get
                Return ResourceManager.GetString("LanguageKorean", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Language: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LanguageLabel() As String
            Get
                Return ResourceManager.GetString("LanguageLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Spanish 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LanguageSpanish() As String
            Get
                Return ResourceManager.GetString("LanguageSpanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Log Probability Threshold: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LogProbThresholdLabel() As String
            Get
                Return ResourceManager.GetString("LogProbThresholdLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Max Context: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MaxContextLabel() As String
            Get
                Return ResourceManager.GetString("MaxContextLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Max Segment Length: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MaxLengthLabel() As String
            Get
                Return ResourceManager.GetString("MaxLengthLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Model Path: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ModelPathLabel() As String
            Get
                Return ResourceManager.GetString("ModelPathLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Do Not Use Previous Audio Context 的本地化字符串。
        '''</summary>
        Public ReadOnly Property NoContextCheckBox() As String
            Get
                Return ResourceManager.GetString("NoContextCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No CSV data to save 的本地化字符串。
        '''</summary>
        Public ReadOnly Property NoCsvDataToSave() As String
            Get
                Return ResourceManager.GetString("NoCsvDataToSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No Temperature Fallback 的本地化字符串。
        '''</summary>
        Public ReadOnly Property NoFallbackCheckBox() As String
            Get
                Return ResourceManager.GetString("NoFallbackCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Do Not Use GPU 的本地化字符串。
        '''</summary>
        Public ReadOnly Property NoGPUCheckBox() As String
            Get
                Return ResourceManager.GetString("NoGPUCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No Speech Threshold: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property NoSpeechThresholdLabel() As String
            Get
                Return ResourceManager.GetString("NoSpeechThresholdLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No Timestamps 的本地化字符串。
        '''</summary>
        Public ReadOnly Property NoTimestampsCheckBox() As String
            Get
                Return ResourceManager.GetString("NoTimestampsCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Segment Index Offset: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property OffsetSegmentLabel() As String
            Get
                Return ResourceManager.GetString("OffsetSegmentLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Time Offset (ms): 的本地化字符串。
        '''</summary>
        Public ReadOnly Property OffsetTimeLabel() As String
            Get
                Return ResourceManager.GetString("OffsetTimeLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 OpenVINO Device: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property OpenVINODeviceLabel() As String
            Get
                Return ResourceManager.GetString("OpenVINODeviceLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Output Merged to CSV 的本地化字符串。
        '''</summary>
        Public ReadOnly Property OutputToCsvCheckBox() As String
            Get
                Return ResourceManager.GetString("OutputToCsvCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Output to File 的本地化字符串。
        '''</summary>
        Public ReadOnly Property OutputToFileCheckBox() As String
            Get
                Return ResourceManager.GetString("OutputToFileCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Parameter Preview 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ParameterPreviewExpander() As String
            Get
                Return ResourceManager.GetString("ParameterPreviewExpander", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Port: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property PortLabel() As String
            Get
                Return ResourceManager.GetString("PortLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Print Colors 的本地化字符串。
        '''</summary>
        Public ReadOnly Property PrintColorsCheckBox() As String
            Get
                Return ResourceManager.GetString("PrintColorsCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Print Progress 的本地化字符串。
        '''</summary>
        Public ReadOnly Property PrintProgressCheckBox() As String
            Get
                Return ResourceManager.GetString("PrintProgressCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Print Real-time Output 的本地化字符串。
        '''</summary>
        Public ReadOnly Property PrintRealtimeCheckBox() As String
            Get
                Return ResourceManager.GetString("PrintRealtimeCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Print Special Tokens 的本地化字符串。
        '''</summary>
        Public ReadOnly Property PrintSpecialCheckBox() As String
            Get
                Return ResourceManager.GetString("PrintSpecialCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Processors: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ProcessorsLabel() As String
            Get
                Return ResourceManager.GetString("ProcessorsLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Initial Prompt: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property PromptLabel() As String
            Get
                Return ResourceManager.GetString("PromptLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Public Folder Path: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property PublicPathLabel() As String
            Get
                Return ResourceManager.GetString("PublicPathLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Request Path: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property RequestPathLabel() As String
            Get
                Return ResourceManager.GetString("RequestPathLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 JSON 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ResponseFormatJson() As String
            Get
                Return ResourceManager.GetString("ResponseFormatJson", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Response Format: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ResponseFormatLabel() As String
            Get
                Return ResourceManager.GetString("ResponseFormatLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 SRT 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ResponseFormatSrt() As String
            Get
                Return ResourceManager.GetString("ResponseFormatSrt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Text 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ResponseFormatText() As String
            Get
                Return ResourceManager.GetString("ResponseFormatText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Verbose JSON 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ResponseFormatVerboseJson() As String
            Get
                Return ResourceManager.GetString("ResponseFormatVerboseJson", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 VTT 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ResponseFormatVtt() As String
            Get
                Return ResourceManager.GetString("ResponseFormatVtt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Server Executable: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ServerExecutablePathLabel() As String
            Get
                Return ResourceManager.GetString("ServerExecutablePathLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Server Output 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ServerOutputExpander() As String
            Get
                Return ResourceManager.GetString("ServerOutputExpander", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 [{0}] {1} 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ServerOutputLine() As String
            Get
                Return ResourceManager.GetString("ServerOutputLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Server Status: Running 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ServerStatusRunning() As String
            Get
                Return ResourceManager.GetString("ServerStatusRunning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Server Status: Starting... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ServerStatusStarting() As String
            Get
                Return ResourceManager.GetString("ServerStatusStarting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Server Status: Stopped 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ServerStatusStopped() As String
            Get
                Return ResourceManager.GetString("ServerStatusStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Split on Word 的本地化字符串。
        '''</summary>
        Public ReadOnly Property SplitOnWordCheckBox() As String
            Get
                Return ResourceManager.GetString("SplitOnWordCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Start Server 的本地化字符串。
        '''</summary>
        Public ReadOnly Property StartServerButton() As String
            Get
                Return ResourceManager.GetString("StartServerButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Start 的本地化字符串。
        '''</summary>
        Public ReadOnly Property StartTranscriptionButton() As String
            Get
                Return ResourceManager.GetString("StartTranscriptionButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Stop Server 的本地化字符串。
        '''</summary>
        Public ReadOnly Property StopServerButton() As String
            Get
                Return ResourceManager.GetString("StopServerButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Suppress Non-Speech Tokens 的本地化字符串。
        '''</summary>
        Public ReadOnly Property SuppressNonSpeechCheckBox() As String
            Get
                Return ResourceManager.GetString("SuppressNonSpeechCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Threads: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ThreadsLabel() As String
            Get
                Return ResourceManager.GetString("ThreadsLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 TinyDiarize 的本地化字符串。
        '''</summary>
        Public ReadOnly Property TinyDiarizeCheckBox() As String
            Get
                Return ResourceManager.GetString("TinyDiarizeCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Added to CSV collection 的本地化字符串。
        '''</summary>
        Public ReadOnly Property TranscriptionAddedToCsv() As String
            Get
                Return ResourceManager.GetString("TranscriptionAddedToCsv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Translate to English 的本地化字符串。
        '''</summary>
        Public ReadOnly Property TranslateCheckBox() As String
            Get
                Return ResourceManager.GetString("TranslateCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Update Preview 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UpdatePreviewButton() As String
            Get
                Return ResourceManager.GetString("UpdatePreviewButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Enable VAD 的本地化字符串。
        '''</summary>
        Public ReadOnly Property VADCheckBox() As String
            Get
                Return ResourceManager.GetString("VADCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 VAD Options 的本地化字符串。
        '''</summary>
        Public ReadOnly Property VADEnhancerExpander() As String
            Get
                Return ResourceManager.GetString("VADEnhancerExpander", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 VAD Max Speech Duration (s): 的本地化字符串。
        '''</summary>
        Public ReadOnly Property VADMaxSpeechDurationLabel() As String
            Get
                Return ResourceManager.GetString("VADMaxSpeechDurationLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 VAD Min Silence Duration (ms): 的本地化字符串。
        '''</summary>
        Public ReadOnly Property VADMinSilenceDurationLabel() As String
            Get
                Return ResourceManager.GetString("VADMinSilenceDurationLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 VAD Min Speech Duration (ms): 的本地化字符串。
        '''</summary>
        Public ReadOnly Property VADMinSpeechDurationLabel() As String
            Get
                Return ResourceManager.GetString("VADMinSpeechDurationLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 VAD Model: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property VADModelLabel() As String
            Get
                Return ResourceManager.GetString("VADModelLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 VAD Samples Overlap (s): 的本地化字符串。
        '''</summary>
        Public ReadOnly Property VADSamplesOverlapLabel() As String
            Get
                Return ResourceManager.GetString("VADSamplesOverlapLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 VAD Speech Padding (ms): 的本地化字符串。
        '''</summary>
        Public ReadOnly Property VADSpeechPadLabel() As String
            Get
                Return ResourceManager.GetString("VADSpeechPadLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 VAD Threshold: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property VADThresholdLabel() As String
            Get
                Return ResourceManager.GetString("VADThresholdLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Word Threshold: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property WordThresholdLabel() As String
            Get
                Return ResourceManager.GetString("WordThresholdLabel", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
